name: Docs

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:

env:
  CI: true
  FORCE_COLOR: 2
  NODE: 15.x

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - run: java -version

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ env.NODE }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.OS }}-node-v${{ env.NODE }}-

      - name: Install npm dependencies
        # TODO: switch back to `npm ci` when https://github.com/npm/cli/issues/1905 is fixed
        run: npm install

      - name: Test docs
        run: npm run docs
